config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :participations
  resources :matches
  resources :places do
    resources :arenas, controller: "places/arenas"
  end
  resources :addresses
  resources :positions
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
end

app/models/position.rb
class Position < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
end

app/controllers/positions_controller.rb
class PositionsController < AdminController
  before_action :set_position, only: [:edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @positions = Position.all
  end

  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to positions_path, notice: 'Position was successfully created.' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to positions_path, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name)
    end
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <br />

  <div class="actions">
    <%= link_to 'Voltar', positions_path, class: "btn btn-primary" %>
    <%= f.submit "Salvar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/positions/edit.html.erb
<h2>Editar Posição: <%= @position.name %></h2>

<div class="col-lg-8 center-block">
  <%= render 'form' %>
</div>

app/views/positions/index.html.erb
<h2>Posições</h2>

<div class="col-lg-8 center-block">
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @positions.each do |position| %>
        <tr>
          <td><%= position.name %></td>
          <td><%= link_to 'Editar', edit_position_path(position), class: "btn-sm btn-warning" %> <%= link_to 'Remover', position, method: :delete, data: { confirm: 'Tem certeza?' }, class: "btn-sm btn-danger" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to '+ Nova Posição', new_position_path, class: "btn btn-success" %>
</div>

app/views/positions/new.html.erb
<h2>Nova Posição</h2>

<div class="col-lg-4 center-block">
  <%= render 'form' %>
</div>