config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :participations
  resources :matches
  resources :places do
    resources :arenas, controller: "places/arenas"
  end
  resources :addresses
  resources :positions
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_one :address
  has_many :arenas

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :arenas
end

app/models/place/arena.rb
class Place::Arena < ActiveRecord::Base
  KINDS = {
    beach_soccer: "Areia",
    natural: "Campo",
    futsal: "Salão",
    society: "Society"
  }

  belongs_to :place
end

app/controllers/places/arenas_controller.rb
module Places
  class ArenasController < AdminController
    before_action :set_arena, only: [:show, :edit, :update, :destroy]

    def index
      @arenas = set_place.arenas
    end

    def new
      @arena = set_place.arenas.build
    end

    def edit
    end

    def create
      @arena = set_place.arenas.build(arena_params)

      if @arena.save
        redirect_to place_arenas_path(set_place), notice: 'Arena was successfully created.'
      else
        render :new
      end
    end

    def update
      if @arena.update(arena_params)
        redirect_to place_arenas_path(set_place), notice: 'Arena was successfully updated.'
      else
        render :edit
        render json: @places_arena.errors, status: :unprocessable_entity
      end
    end

    def destroy
      if @arena.destroy
        redirect_to place_arenas_path(set_place), notice: 'Arena was successfully destroyed.'
      else
        redirect_to place_arenas_path(set_place), error: 'Arena was not destroyed.'
      end
    end

    private
    def set_place
      @place ||= Place.find(params[:place_id])
    end

    def set_arena
      @arena = set_place.arenas.find(params[:id])
    end

    def arena_params
      params.require(:place_arena).permit(:name, :width, :length, :kind)
    end
  end

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
    @place.build_address
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to places_path, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to places_path, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, address_attributes: [:state, :city, :district, :street, :zip_code])
    end
end

app/views/places/arenas/_form.html.erb
<%= form_for(@arena) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :width %>
    <%= f.text_field :width, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :length %>
    <%= f.text_field :length, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :kind %>
    <%= f.select :kind, Place::Arena::KINDS.map { |key, value| [value, key] }, { include_blank: true }, class: "form-control" %>
  </div>
  <br />

  <div class="actions">
    <%= link_to 'Voltar', place_arenas_path(@place), class: "btn btn-primary" %>
    <%= f.submit "Salvar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/places/arenas/edit.html.erb
<h1>Editing Places Arena</h1>

<%= render 'form' %>

<%= link_to 'Show', @places_arena %> |
<%= link_to 'Back', places_arenas_path %>

app/views/places/arenas/index.html.erb
<h2>Arenas em <%= @place.name %></h2>

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Dimensões</th>
      <th>Tipo</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @arenas.each do |arena| %>
      <td><%= arena.name %></td>
      <td><%= "#{ arena.width }x#{ arena.length }" %></td>
      <td><%= arena.kind %></td>
      <td><%= link_to "Alterar", edit_place_arena_path(@place, arena), class: "btn-sm btn-warning" %> <%= link_to 'Remover', place_arena_path(@place, arena), method: :delete, data: { confirm: 'Tem certeza que deseja remover?' }, class: "btn-sm btn-danger" %></td>
    <% end %>
  </tbody>
</table>

<%= link_to "Voltar", places_path, class: "btn btn-primary" %>
<%= link_to "+ Nova Arena", new_place_arena_path, class: "btn btn-success" %>

app/views/places/arenas/new.html.erb
<h2>Nova Arena em <%= @place.name %></h2>

<div class="col-lg-6 center-block">
  <%= render 'form' %>
</div>