config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  resources :participations
  resources :matches
  resources :places do
    resources :arenas, controller: "places/arenas"
  end
  resources :addresses
  resources :positions
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pelada</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Pelada", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="<%= 'active' if controller_name == "pages" && action_name == "home" %>"><%= link_to "Página Inicial", root_path %></li>
            <li class="<%= 'active' if controller_name == "matches" && action_name == "new" %>"><%= link_to "Nova Pelada", new_match_path %></li>
            <% if current_user && current_user.admin? %>
              <li class="<%= 'active' if controller_name == "places" %>"><%= link_to "Locais", places_path %></li>
              <li class="<%= 'active' if controller_name == "positions" %>"><%= link_to "Posições", positions_path %></li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Alterar dados", edit_user_registration_path(current_user) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Registro", new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>